### ISSUE TITLE
Different executions with same random seed have different results.

### ISSUE THREAD

**Issue by dranidis** [dranidis/animal-farm#7]
FarmRandom is a Singleton factory providing the same Random instance to all classes.

FarmRandom.isFake=true, before the first getInstance makes sure that same random numbers are provided by initializing with seed 0: Random(0).

Tests show that this works, but different executions of the program have differences.

How to reproduce:
```
mvn clean install
java -cp target/classes com.asdt.farm.App > output1
java -cp target/classes com.asdt.farm.App > output2
diff output1 output2
```

**Comment by KubiGR** [comment]
`FarmRandom.isfake = true;`
This surely changes the FarmRandom attribute to true?

For me it says Class not loaded

**Comment by dranidis** [comment]
Yes it does. I can run it normally with the given commands. First lines of execution are:

SAME RANDOM NUMBERS WITH SEED: 0
Step: 1
Lucy is moving
Lucy: stamina: 9, energy: 2

Class not loaded?

**Comment by mmichailidis** [comment]
Which class is not loaded? the random?

**Comment by mmichailidis** [comment]
AH YES that is my bad! hahahahaha i just recalled why :) 
When someone would throw some food the food would not land perfectly on top right? sooo
check Feeder#23 line
`Collections.shuffle(this.currentFood);`

**Comment by dranidis** [comment]
shuffle!

I forgot about this. I saw it the first time I looked at the code!!!
Problem solved.

        Collections.shuffle(this.currentFood,
FarmRandom.getInstance().getRandom());

Works now.
